api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    collection:
        pagination:
            enabled: false
            items_per_page: 25
            client_enabled: true
            client_items_per_page: true
            items_per_page_parameter_name: "count"